-- Slim derived table serving prepare_batter_balls() and load_qualifying_batters()
-- in src/optimization.py.
-- Each row = one ball that passes the _BATTER_QUERY filter (type='X', bb_type in
-- fly_ball/line_drive, home runs etc. excluded) and has flight_time > 0.5. Columns
-- store the already-computed derived values (ball_x/ball_y/flight_time/spray_angle);
-- raw columns like hc_x/hc_y are not stored, so the physics formula logic stays in
-- exactly one place, physics.py.
-- Generated by scripts/precompute_batter_balls.py; not maintained by hand.
CREATE TABLE IF NOT EXISTS precomputed_batter_balls (
    batter        INTEGER          NOT NULL,
    game_year     SMALLINT         NOT NULL,
    stand         CHAR(1)          NOT NULL,
    ball_x        DOUBLE PRECISION NOT NULL,
    ball_y        DOUBLE PRECISION NOT NULL,
    flight_time   DOUBLE PRECISION NOT NULL,
    launch_speed  DOUBLE PRECISION NOT NULL,
    launch_angle  DOUBLE PRECISION NOT NULL,
    spray_angle   DOUBLE PRECISION NOT NULL,
    bb_type       TEXT             NOT NULL   -- 'fly_ball' | 'line_drive' (for ball-type filtering on the integrated page)
);

CREATE INDEX IF NOT EXISTS idx_pbb_batter_year ON precomputed_batter_balls (batter, game_year);
CREATE INDEX IF NOT EXISTS idx_pbb_year         ON precomputed_batter_balls (game_year);
