-- Offline-precomputed infield positioning optimization results, serving the web
-- infield page (real-time computation online is not feasible: n_restarts=20 takes
-- 4 seconds locally and tens of seconds or more on Render's 0.1 CPU).
-- Each row = one (batter, year): for batters with >= a threshold (default 50)
-- ground balls that year, the four infielders' optimized positioning using that
-- year's historical ground balls with a high n_restarts (default 50, no need to
-- economize offline), plus the comparison expected out rate under that year's
-- league-average positioning.
-- Generated by scripts/precompute_if_optimize.py; not maintained by hand.
CREATE TABLE IF NOT EXISTS precomputed_if_positions (
    batter          INTEGER          NOT NULL,
    game_year       SMALLINT         NOT NULL,
    stand           CHAR(1)          NOT NULL,
    n_gb            INTEGER          NOT NULL,
    hp_to_1b        DOUBLE PRECISION NOT NULL,
    exp_outs_league DOUBLE PRECISION NOT NULL,
    exp_outs_opt    DOUBLE PRECISION NOT NULL,
    angle_1b        DOUBLE PRECISION NOT NULL,
    depth_1b        DOUBLE PRECISION NOT NULL,
    angle_2b        DOUBLE PRECISION NOT NULL,
    depth_2b        DOUBLE PRECISION NOT NULL,
    angle_3b        DOUBLE PRECISION NOT NULL,
    depth_3b        DOUBLE PRECISION NOT NULL,
    angle_ss        DOUBLE PRECISION NOT NULL,
    depth_ss        DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (batter, game_year)
);
