-- 自動從 data/raw/statcast/2025.parquet 的欄位結構生成（119 個欄位，型態對應 pandas/pyarrow dtype）
-- 一個 pitch (球) 由 (game_pk, at_bat_number, pitch_number) 唯一識別，設為複合主鍵

DROP TABLE IF EXISTS statcast;

CREATE TABLE statcast (
    pitch_type TEXT,
    game_date TIMESTAMP,
    release_speed DOUBLE PRECISION,
    release_pos_x DOUBLE PRECISION,
    release_pos_z DOUBLE PRECISION,
    player_name TEXT,
    batter BIGINT,
    pitcher BIGINT,
    events TEXT,
    description TEXT,
    spin_dir BIGINT,
    spin_rate_deprecated BIGINT,
    break_angle_deprecated BIGINT,
    break_length_deprecated BIGINT,
    zone BIGINT,
    des TEXT,
    game_type TEXT,
    stand TEXT,
    p_throws TEXT,
    home_team TEXT,
    away_team TEXT,
    type TEXT,
    hit_location BIGINT,
    bb_type TEXT,
    balls BIGINT,
    strikes BIGINT,
    game_year BIGINT,
    pfx_x DOUBLE PRECISION,
    pfx_z DOUBLE PRECISION,
    plate_x DOUBLE PRECISION,
    plate_z DOUBLE PRECISION,
    on_3b BIGINT,
    on_2b BIGINT,
    on_1b BIGINT,
    outs_when_up BIGINT,
    inning BIGINT,
    inning_topbot TEXT,
    hc_x DOUBLE PRECISION,
    hc_y DOUBLE PRECISION,
    tfs_deprecated BIGINT,
    tfs_zulu_deprecated BIGINT,
    umpire BIGINT,
    sv_id BIGINT,
    vx0 DOUBLE PRECISION,
    vy0 DOUBLE PRECISION,
    vz0 DOUBLE PRECISION,
    ax DOUBLE PRECISION,
    ay DOUBLE PRECISION,
    az DOUBLE PRECISION,
    sz_top DOUBLE PRECISION,
    sz_bot DOUBLE PRECISION,
    hit_distance_sc BIGINT,
    launch_speed DOUBLE PRECISION,
    launch_angle BIGINT,
    effective_speed DOUBLE PRECISION,
    release_spin_rate BIGINT,
    release_extension DOUBLE PRECISION,
    game_pk BIGINT,
    fielder_2 BIGINT,
    fielder_3 BIGINT,
    fielder_4 BIGINT,
    fielder_5 BIGINT,
    fielder_6 BIGINT,
    fielder_7 BIGINT,
    fielder_8 BIGINT,
    fielder_9 BIGINT,
    release_pos_y DOUBLE PRECISION,
    estimated_ba_using_speedangle DOUBLE PRECISION,
    estimated_woba_using_speedangle DOUBLE PRECISION,
    woba_value DOUBLE PRECISION,
    woba_denom BIGINT,
    babip_value BIGINT,
    iso_value BIGINT,
    launch_speed_angle BIGINT,
    at_bat_number BIGINT,
    pitch_number BIGINT,
    pitch_name TEXT,
    home_score BIGINT,
    away_score BIGINT,
    bat_score BIGINT,
    fld_score BIGINT,
    post_away_score BIGINT,
    post_home_score BIGINT,
    post_bat_score BIGINT,
    post_fld_score BIGINT,
    if_fielding_alignment TEXT,
    of_fielding_alignment TEXT,
    spin_axis BIGINT,
    delta_home_win_exp DOUBLE PRECISION,
    delta_run_exp DOUBLE PRECISION,
    bat_speed DOUBLE PRECISION,
    swing_length DOUBLE PRECISION,
    miss_distance DOUBLE PRECISION,
    estimated_slg_using_speedangle DOUBLE PRECISION,
    delta_pitcher_run_exp DOUBLE PRECISION,
    hyper_speed DOUBLE PRECISION,
    home_score_diff BIGINT,
    bat_score_diff BIGINT,
    home_win_exp DOUBLE PRECISION,
    bat_win_exp DOUBLE PRECISION,
    age_pit_legacy BIGINT,
    age_bat_legacy BIGINT,
    age_pit BIGINT,
    age_bat BIGINT,
    n_thruorder_pitcher BIGINT,
    n_priorpa_thisgame_player_at_bat BIGINT,
    pitcher_days_since_prev_game BIGINT,
    batter_days_since_prev_game BIGINT,
    pitcher_days_until_next_game BIGINT,
    batter_days_until_next_game BIGINT,
    api_break_z_with_gravity DOUBLE PRECISION,
    api_break_x_arm DOUBLE PRECISION,
    api_break_x_batter_in DOUBLE PRECISION,
    arm_angle DOUBLE PRECISION,
    attack_angle DOUBLE PRECISION,
    attack_direction DOUBLE PRECISION,
    swing_path_tilt DOUBLE PRECISION,
    intercept_ball_minus_batter_pos_x_inches DOUBLE PRECISION,
    intercept_ball_minus_batter_pos_y_inches DOUBLE PRECISION,
    PRIMARY KEY (game_pk, at_bat_number, pitch_number)
);
