-- Our own model's infield OAA (used by the web leaderboard page); the comparison
-- table is if_oaa_leaderboard (official).
-- model_oaa is position-centered Sum(is_out - p_hat), where p_hat comes from the
-- evaluation GBM (no fielder information).
-- position is the position with the most attributed balls. player_name comes from
-- the official leaderboard; unmatched players get NULL (the leaderboard page only
-- shows players with a name). See scripts/evaluate_if_2025.py for methodology.
-- Generated by scripts/precompute_if_model_oaa.py; not maintained by hand.
CREATE TABLE IF NOT EXISTS if_model_oaa (
    player_id   INTEGER          NOT NULL,
    player_name TEXT,
    position    TEXT             NOT NULL,
    year        SMALLINT         NOT NULL,
    model_oaa   DOUBLE PRECISION NOT NULL,
    n_balls     INTEGER          NOT NULL,
    PRIMARY KEY (player_id, year)
);
