-- Slim derived table serving get_batter_stand() in src/optimization.py.
-- One row per (batter, game_year), storing the most common stand across "all
-- plate appearances" that batter had that year (not restricted by bb_type,
-- unlike precomputed_batter_balls's filter, so this can't share a table with it).
-- Generated by scripts/precompute_batter_balls.py; not maintained by hand.
CREATE TABLE IF NOT EXISTS precomputed_batter_stand (
    batter     INTEGER  NOT NULL,
    game_year  SMALLINT NOT NULL,
    stand      CHAR(1)  NOT NULL,
    PRIMARY KEY (batter, game_year)
);
