-- Per-ball data for the infield page charts: the historical ground balls
-- corresponding to each (batter, year) in precomputed_if_positions (same filter
-- as src/if_optimize.fetch_batter_gbs), including per-ball out probability under
-- both positioning setups (from the optimization GLM), for frontend coloring
-- (mirroring the outfield SprayChart's catch_prob coloring).
-- ball_x/ball_y are hc_x/hc_y converted to feet (home plate origin, +x toward the
-- 1B side).
-- Note on semantics: this is the position where Statcast recorded the ball being
-- fielded/picked up, not where the batted ball actually landed -- out balls skew
-- systematically shallow (median ~118 ft) and hits skew deep (~224 ft), since it's
-- a function of both the outcome and the fielding play. Display use only; do not
-- use this to build batter distributions (see the endogeneity discussion in
-- src/if_dataset.py).
-- Generated by scripts/precompute_if_optimize.py; not maintained by hand.
CREATE TABLE IF NOT EXISTS precomputed_if_gbs (
    batter       INTEGER          NOT NULL,
    game_year    SMALLINT         NOT NULL,
    spray_deg    DOUBLE PRECISION NOT NULL,
    ball_x       DOUBLE PRECISION NOT NULL,
    ball_y       DOUBLE PRECISION NOT NULL,
    launch_speed DOUBLE PRECISION NOT NULL,
    launch_angle DOUBLE PRECISION NOT NULL,
    is_out       BOOLEAN          NOT NULL,
    p_out_league DOUBLE PRECISION NOT NULL,
    p_out_opt    DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pig_batter_year ON precomputed_if_gbs (batter, game_year);
