-- Slim derived table serving the display-only infield popups on
-- /api/optimize_integrated.
-- Popup positioning has no leverage (98.6% out rate, catchable from any
-- positioning) so it does not participate in any optimization; this table exists
-- purely for the visual completeness of "all of the batter's balls in play" on
-- the integrated page.
-- ball_x/ball_y are converted from hc using the x2.5 ft convention (same display-
-- coordinate convention as precomputed_if_gbs; hc is a recorded coordinate, not
-- the actual landing spot -- fine for display, not for building distributions,
-- see the known limitation noted in ARCHITECTURE.md).
-- is_out = events not in (single, double, triple, field_error).
-- Generated by scripts/precompute_batter_popups.py; not maintained by hand.
CREATE TABLE IF NOT EXISTS precomputed_batter_popups (
    batter        INTEGER          NOT NULL,
    game_year     SMALLINT         NOT NULL,
    ball_x        DOUBLE PRECISION NOT NULL,
    ball_y        DOUBLE PRECISION NOT NULL,
    launch_speed  DOUBLE PRECISION,
    is_out        BOOLEAN          NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pbp_batter_year ON precomputed_batter_popups (batter, game_year);
